# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ieb-ufsc/PycharmProjects/controlDeportivoV3/ui/home.ui'
#
# Created: Tue Mar 17 12:06:35 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(631, 570)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.layoutWidget = QtGui.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 10, 541, 75))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Mukti Narrow"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.Readtext = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.Readtext.setFont(font)
        self.Readtext.setAlignment(QtCore.Qt.AlignCenter)
        self.Readtext.setObjectName(_fromUtf8("Readtext"))
        self.gridLayout_2.addWidget(self.Readtext, 0, 1, 1, 1)
        self.buttongo = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.buttongo.setFont(font)
        self.buttongo.setObjectName(_fromUtf8("buttongo"))
        self.gridLayout_2.addWidget(self.buttongo, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 149, 160, 95))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ButtonStart = QtGui.QPushButton(self.layoutWidget1)
        self.ButtonStart.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.ButtonStart.setFont(font)
        self.ButtonStart.setObjectName(_fromUtf8("ButtonStart"))
        self.verticalLayout.addWidget(self.ButtonStart)
        self.ButtonPosition = QtGui.QPushButton(self.layoutWidget1)
        self.ButtonPosition.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.ButtonPosition.setFont(font)
        self.ButtonPosition.setObjectName(_fromUtf8("ButtonPosition"))
        self.verticalLayout.addWidget(self.ButtonPosition)
        self.ButtonStop = QtGui.QPushButton(self.layoutWidget1)
        self.ButtonStop.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.ButtonStop.setFont(font)
        self.ButtonStop.setObjectName(_fromUtf8("ButtonStop"))
        self.verticalLayout.addWidget(self.ButtonStop)
        self.layoutWidget2 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(420, 140, 163, 121))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.labelintervaloRR = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.labelintervaloRR.setFont(font)
        self.labelintervaloRR.setAlignment(QtCore.Qt.AlignCenter)
        self.labelintervaloRR.setObjectName(_fromUtf8("labelintervaloRR"))
        self.gridLayout.addWidget(self.labelintervaloRR, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.labelbpsout = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.labelbpsout.setFont(font)
        self.labelbpsout.setAlignment(QtCore.Qt.AlignCenter)
        self.labelbpsout.setObjectName(_fromUtf8("labelbpsout"))
        self.gridLayout.addWidget(self.labelbpsout, 2, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(0, 280, 631, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(0, 90, 631, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.layoutWidget3 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(7, 300, 611, 254))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.layoutWidget3)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.plotEMG = QtGui.QRadioButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plotEMG.setFont(font)
        self.plotEMG.setObjectName(_fromUtf8("plotEMG"))
        self.horizontalLayout_3.addWidget(self.plotEMG)
        self.plotVFC = QtGui.QRadioButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plotVFC.setFont(font)
        self.plotVFC.setObjectName(_fromUtf8("plotVFC"))
        self.horizontalLayout_3.addWidget(self.plotVFC)
        self.plotButton = QtGui.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.plotButton.setFont(font)
        self.plotButton.setObjectName(_fromUtf8("plotButton"))
        self.horizontalLayout_3.addWidget(self.plotButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.plot = PlotWidget(self.layoutWidget3)
        self.plot.setObjectName(_fromUtf8("plot"))
        self.verticalLayout_2.addWidget(self.plot)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.layoutWidget4 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(220, 150, 101, 62))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pauseEmgButton = QtGui.QPushButton(self.layoutWidget4)
        self.pauseEmgButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.pauseEmgButton.setFont(font)
        self.pauseEmgButton.setObjectName(_fromUtf8("pauseEmgButton"))
        self.gridLayout_4.addWidget(self.pauseEmgButton, 0, 0, 1, 1)
        self.resetButton = QtGui.QPushButton(self.layoutWidget4)
        self.resetButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.gridLayout_4.addWidget(self.resetButton, 1, 0, 1, 1)
        self.layoutWidget5 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 260, 376, 22))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.tempoProvaout = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tempoProvaout.setFont(font)
        self.tempoProvaout.setObjectName(_fromUtf8("tempoProvaout"))
        self.horizontalLayout.addWidget(self.tempoProvaout)
        self.label_7 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.relojout = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.relojout.setFont(font)
        self.relojout.setAlignment(QtCore.Qt.AlignCenter)
        self.relojout.setObjectName(_fromUtf8("relojout"))
        self.horizontalLayout.addWidget(self.relojout)
        self.arduinoLabel = QtGui.QLabel(self.centralWidget)
        self.arduinoLabel.setGeometry(QtCore.QRect(220, 220, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(11)
        self.arduinoLabel.setFont(font)
        self.arduinoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.arduinoLabel.setObjectName(_fromUtf8("arduinoLabel"))
        self.layoutWidget6 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(41, 105, 541, 25))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget6)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_11 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.activarVFC = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.activarVFC.setFont(font)
        self.activarVFC.setObjectName(_fromUtf8("activarVFC"))
        self.gridLayout_5.addWidget(self.activarVFC, 0, 1, 1, 1)
        self.activarEMG = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.activarEMG.setFont(font)
        self.activarEMG.setObjectName(_fromUtf8("activarEMG"))
        self.gridLayout_5.addWidget(self.activarEMG, 0, 2, 1, 1)
        self.activarIMUS = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.activarIMUS.setFont(font)
        self.activarIMUS.setObjectName(_fromUtf8("activarIMUS"))
        self.gridLayout_5.addWidget(self.activarIMUS, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Interface de Controle", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:11pt; font-weight:600;\">Insira o Nome e # do Teste :</span></p></body></html>", None))
        self.buttongo.setText(_translate("MainWindow", "GO!", None))
        self.ButtonStart.setText(_translate("MainWindow", "Start Capture", None))
        self.ButtonPosition.setText(_translate("MainWindow", "Take Position 1", None))
        self.ButtonStop.setText(_translate("MainWindow", "Stop Capture", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Intervalo RR : </span></p></body></html>", None))
        self.labelintervaloRR.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">-----</span></p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Bpm : </span></p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Variaveis Actuais </span></p></body></html>", None))
        self.labelbpsout.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">-----</span></p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Seleccionar Grafico :</span></p></body></html>", None))
        self.plotEMG.setText(_translate("MainWindow", "EMG", None))
        self.plotVFC.setText(_translate("MainWindow", "VFC", None))
        self.plotButton.setText(_translate("MainWindow", "Plot", None))
        self.pauseEmgButton.setText(_translate("MainWindow", "Pause Emg", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))
        self.label_8.setText(_translate("MainWindow", "Tempo Prova :", None))
        self.tempoProvaout.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">00:00</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Temporizador :</p></body></html>", None))
        self.relojout.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ff0000;\">00:00</span></p></body></html>", None))
        self.arduinoLabel.setText(_translate("MainWindow", "--", None))
        self.label_11.setText(_translate("MainWindow", "Ativar:", None))
        self.activarVFC.setText(_translate("MainWindow", "Registro VFC", None))
        self.activarEMG.setText(_translate("MainWindow", "Registro EMG", None))
        self.activarIMUS.setText(_translate("MainWindow", "Registro Movimiento", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

