# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ieb-ufsc/PycharmProjects/ProjectoHiago/Guide/hometab.ui'
#
# Created: Fri Jun 12 16:57:45 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.setEnabled(True)
        TabWidget.resize(592, 485)
        TabWidget.setMouseTracking(False)
        TabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        TabWidget.setTabPosition(QtGui.QTabWidget.North)
        TabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        TabWidget.setElideMode(QtCore.Qt.ElideNone)
        TabWidget.setTabsClosable(False)
        TabWidget.setMovable(False)
        self.tab = QtGui.QWidget()
        self.tab.setEnabled(True)
        self.tab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tab1 = QtGui.QPushButton(self.tab)
        self.tab1.setGeometry(QtCore.QRect(475, 400, 85, 26))
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(25, 45, 531, 342))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.timeEdit_2 = QtGui.QTimeEdit(self.layoutWidget)
        self.timeEdit_2.setObjectName(_fromUtf8("timeEdit_2"))
        self.gridLayout.addWidget(self.timeEdit_2, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.timeEdit = QtGui.QTimeEdit(self.layoutWidget)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.gridLayout.addWidget(self.timeEdit, 3, 1, 1, 1)
        self.comboBox = QtGui.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.comboBox_2)
        self.gridLayout.addLayout(self.verticalLayout, 11, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 11, 0, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.line_6 = QtGui.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout.addWidget(self.line_6, 12, 0, 1, 2)
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 2)
        self.line_4 = QtGui.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 8, 0, 1, 2)
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 6, 0, 1, 2)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.line_5 = QtGui.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 10, 0, 1, 2)
        self.line_7 = QtGui.QFrame(self.layoutWidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout.addWidget(self.line_7, 0, 0, 1, 2)
        self.comboBox_3 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_3, 7, 1, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_4, 9, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(30, 15, 521, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        TabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setMouseTracking(False)
        self.tab_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalScrollBar = QtGui.QScrollBar(self.tab_2)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(340, 150, 160, 16))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        self.horizontalScrollBar_2 = QtGui.QScrollBar(self.tab_2)
        self.horizontalScrollBar_2.setGeometry(QtCore.QRect(345, 210, 160, 16))
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName(_fromUtf8("horizontalScrollBar_2"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(335, 185, 58, 15))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(345, 130, 21, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalSlider = QtGui.QSlider(self.tab_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(150, 325, 160, 18))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        TabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        TabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget", None))
        self.tab1.setText(_translate("TabWidget", "Continuar", None))
        self.label_2.setText(_translate("TabWidget", "Na noite anterior em que horario você dormiu?", None))
        self.comboBox.setItemText(0, _translate("TabWidget", "Manhã", None))
        self.comboBox.setItemText(1, _translate("TabWidget", "Tarde", None))
        self.comboBox.setItemText(2, _translate("TabWidget", "Noite", None))
        self.comboBox_2.setItemText(0, _translate("TabWidget", "1", None))
        self.comboBox_2.setItemText(1, _translate("TabWidget", "2", None))
        self.comboBox_2.setItemText(2, _translate("TabWidget", "3", None))
        self.label_6.setText(_translate("TabWidget", "<html><head/><body><p>A quanto tempo você não realiza </p><p>atividades fisicas intensas?</p></body></html>", None))
        self.label.setText(_translate("TabWidget", "Qual o período do dia da coleta?", None))
        self.label_5.setText(_translate("TabWidget", "<html><head/><body><p>A quanto tempo você está sem tomar</p><p>cafeina ou energeticos?</p></body></html>", None))
        self.label_4.setText(_translate("TabWidget", "A quanto tempo você está sem se alimentar?", None))
        self.label_3.setText(_translate("TabWidget", "Hoje, você acordo que horas?", None))
        self.comboBox_3.setItemText(0, _translate("TabWidget", "1", None))
        self.comboBox_3.setItemText(1, _translate("TabWidget", "2", None))
        self.comboBox_3.setItemText(2, _translate("TabWidget", "3", None))
        self.comboBox_4.setItemText(0, _translate("TabWidget", "1", None))
        self.comboBox_4.setItemText(1, _translate("TabWidget", "2", None))
        self.comboBox_4.setItemText(2, _translate("TabWidget", "3", None))
        self.label_7.setText(_translate("TabWidget", "Caracterização", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Home", None))
        self.label_8.setText(_translate("TabWidget", "TextLabel", None))
        self.label_9.setText(_translate("TabWidget", "1", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "Tab 2", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), _translate("TabWidget", "Tab3", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TabWidget = QtGui.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

