# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/diegopaez/PycharmProjects/VFCMarjorie/guide/gui.ui'
#
# Created: Mon Jul  6 19:15:09 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.setEnabled(True)
        TabWidget.resize(800, 648)
        TabWidget.setMinimumSize(QtCore.QSize(800, 600))
        TabWidget.setMaximumSize(QtCore.QSize(804, 648))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Latin Modern Sans"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        TabWidget.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Home_Icon_Silhouette_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.setWindowIcon(icon)
        TabWidget.setTabPosition(QtGui.QTabWidget.North)
        TabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab1 = QtGui.QWidget()
        self.tab1.setMinimumSize(QtCore.QSize(800, 600))
        self.tab1.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tab1.setFont(font)
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.graphicsView_2 = QtGui.QGraphicsView(self.tab1)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 0, 800, 600))
        brush = QtGui.QBrush(QtGui.QColor(133, 255, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.graphicsView_2.setBackgroundBrush(brush)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.layoutWidget = QtGui.QWidget(self.tab1)
        self.layoutWidget.setGeometry(QtCore.QRect(315, 440, 176, 149))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.startHome = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Latin Modern Sans"))
        font.setPointSize(14)
        self.startHome.setFont(font)
        self.startHome.setObjectName(_fromUtf8("startHome"))
        self.gridLayout_2.addWidget(self.startHome, 0, 0, 1, 1)
        self.skipHome = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Latin Modern Sans"))
        font.setPointSize(14)
        self.skipHome.setFont(font)
        self.skipHome.setObjectName(_fromUtf8("skipHome"))
        self.gridLayout_2.addWidget(self.skipHome, 2, 0, 1, 1)
        self.stopHome = QtGui.QPushButton(self.layoutWidget)
        self.stopHome.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stopHome.setFont(font)
        self.stopHome.setObjectName(_fromUtf8("stopHome"))
        self.gridLayout_2.addWidget(self.stopHome, 1, 0, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.tab1)
        self.layoutWidget1.setGeometry(QtCore.QRect(190, 5, 419, 426))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Latin Modern Sans"))
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.respirar = QtGui.QLabel(self.layoutWidget1)
        self.respirar.setText(_fromUtf8(""))
        self.respirar.setPixmap(QtGui.QPixmap(_fromUtf8("diaphragmatic_breathing.png")))
        self.respirar.setScaledContents(True)
        self.respirar.setWordWrap(True)
        self.respirar.setObjectName(_fromUtf8("respirar"))
        self.gridLayout.addWidget(self.respirar, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Latin Modern Sans"))
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.temporizador1 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Latin Modern Sans"))
        font.setPointSize(16)
        self.temporizador1.setFont(font)
        self.temporizador1.setAlignment(QtCore.Qt.AlignCenter)
        self.temporizador1.setObjectName(_fromUtf8("temporizador1"))
        self.gridLayout.addWidget(self.temporizador1, 3, 0, 1, 1)
        self.line = QtGui.QFrame(self.tab1)
        self.line.setGeometry(QtCore.QRect(400, 0, 1, 600))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Home_Icon_Silhouette_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.addTab(self.tab1, icon1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setEnabled(False)
        self.tab2.setMinimumSize(QtCore.QSize(800, 600))
        self.tab2.setMaximumSize(QtCore.QSize(800, 600))
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.graphicsView = QtGui.QGraphicsView(self.tab2)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.graphicsView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.graphicsView.setFrameShadow(QtGui.QFrame.Sunken)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(15, 161, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.graphicsView.setBackgroundBrush(brush)
        self.graphicsView.setInteractive(True)
        self.graphicsView.setCacheMode(QtGui.QGraphicsView.CacheNone)
        self.graphicsView.setTransformationAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.graphicsView.setResizeAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.layoutWidget2 = QtGui.QWidget(self.tab2)
        self.layoutWidget2.setGeometry(QtCore.QRect(290, 480, 226, 47))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.start = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Latin Modern Sans"))
        font.setPointSize(14)
        self.start.setFont(font)
        self.start.setObjectName(_fromUtf8("start"))
        self.gridLayout_3.addWidget(self.start, 0, 0, 1, 1)
        self.stop = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Latin Modern Sans"))
        font.setPointSize(14)
        self.stop.setFont(font)
        self.stop.setObjectName(_fromUtf8("stop"))
        self.gridLayout_3.addWidget(self.stop, 0, 1, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.tab2)
        self.layoutWidget3.setGeometry(QtCore.QRect(325, 360, 156, 88))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Latin Modern Sans"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.temporizador2 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.temporizador2.setFont(font)
        self.temporizador2.setAlignment(QtCore.Qt.AlignCenter)
        self.temporizador2.setObjectName(_fromUtf8("temporizador2"))
        self.gridLayout_4.addWidget(self.temporizador2, 1, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab2)
        self.line_2.setGeometry(QtCore.QRect(400, 0, 1, 600))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Dumbbell_training_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.addTab(self.tab2, icon2, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "Breathing Trainer", None))
        self.startHome.setText(_translate("TabWidget", "Start", None))
        self.skipHome.setText(_translate("TabWidget", "Skip", None))
        self.stopHome.setText(_translate("TabWidget", "Stop", None))
        self.label_2.setText(_translate("TabWidget", "Breathing Training", None))
        self.label_4.setText(_translate("TabWidget", "Wait For Calibration", None))
        self.temporizador1.setText(_translate("TabWidget", "3:00", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab1), _translate("TabWidget", "Home", None))
        self.start.setText(_translate("TabWidget", "Start", None))
        self.stop.setText(_translate("TabWidget", "Stop", None))
        self.label.setText(_translate("TabWidget", "IN", None))
        self.temporizador2.setText(_translate("TabWidget", "5:00", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab2), _translate("TabWidget", "Training", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TabWidget = QtGui.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

